### ISSUE TITLE
feature add arabic

### ISSUE THREAD

**Issue by khatibomar** [Destaq/wallpaper-learn#1]
I am going to add Arabic support . I am busy in exams right now . I will implement it .
If some one here know Arabic and can implement it go forward , because I need month and half :p to finish.

**Comment by khatibomar** [comment]
If some one need to work it before me .
Here things to take in consider , csv is the file where you can add arabic-other_language
also if it's make some troubles look at right to left (RTL) in python if you got a problem with arabic :)

**Comment by Destaq** [comment]
Alright, thank you for letting me know. I'll leave this issue open in case anyone wants to implement it in the meantime. However, since the Reddit post did not reach as many people as I wanted it to, perhaps if you or I reshared it once more then we may be able to find more people willing to help (for example in Arabic).

**Comment by khatibomar** [comment]
This issue is on my mind , I need 2 more weeks to finish exams, 
due corona the exams delayed for more 1 week.

**Comment by Destaq** [comment]
No problem.

**Comment by khatibomar** [comment]
Finally , I finish and take a Rest let's start coding :)

**Comment by khatibomar** [comment]
I made a PR for translations, but I don't know how the code works yet. Maybe tomorrow I will test it on a virtual machine.

**Comment by Destaq** [comment]
Closed as PR has been merged.
